name: movie_trailer
description: s
version: 1.1.4

environment:
  sdk: ">=2.12.0 <3.0.0"
module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter 
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  enum_to_string: ^1.0.9
  flare_flutter: 3.0.2
  flare_dart: 2.2.5
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  basic_utils: ^4.2.0
  path_provider: ^2.0.9
  http: ^0.13.4
  get_it: ^7.2.0
  flutter_screenutil: ^5.0.3
  connectivity_plus: ^2.3.0
  event: ^2.0.5
  get: ^4.6.1
  devicelocale: ^0.5.0
  diacritic: ^0.1.3
  equatable: ^2.0.3
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6

flutter:
  uses-material-design: true
  assets:


    - assets/images/star.flr
    - assets/images/star.png
    - assets/images/logo.png
    - assets/images/exit.png
    - assets/images/home_icon.png
    - assets/images/bg.jpg
    - assets/images/loading.gif
    
    - assets/images/logo.png
    - assets/images/Favorite.jpg

